"""create planner models

Revision ID: 529be3eda0fd
Revises: 
Create Date: 2026-08-18 18:33:27.622281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '529be3eda0fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('mana', sa.Integer(), nullable=False),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('physical', sa.Integer(), nullable=False),
    sa.Column('creativity', sa.Integer(), nullable=False),
    sa.Column('social', sa.Integer(), nullable=False),
    sa.Column('mental', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('mana_reward', sa.Integer(), nullable=False),
    sa.Column('stat', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('daily_entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['daily_entry_id'], ['daily_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('daily_entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['daily_entry_id'], ['daily_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('scheduled_time', sa.String(length=10), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_important', sa.Boolean(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('stat', sa.String(length=50), nullable=True),
    sa.Column('daily_entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['daily_entry_id'], ['daily_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('quests')
    op.drop_table('activities')
    op.drop_table('daily_entries')
    # ### end Alembic commands ###
